In [1]:
import os
import cv2
import csv
import glob
import random
import numpy as np
from pathlib import Path, PureWindowsPath

In [2]:
os.chdir(r'D:\ffmpeg\directorios\FILES')
videos = glob.glob(r'*.mp4')
videos.sort(key = len)
samples = np.genfromtxt(r'D:\ffmpeg\directorios\distorted-mp4\TOTALSCORE.csv',usecols=np.arange(1,6))
rsamples = np.reshape(samples,(800,1))
sfile = open(r'D:\ffmpeg\directorios\experiments\scores.csv','w')
print(rsamples, file = sfile)
vsize = len(videos)
ssize = len(rsamples)
print(vsize)
print(ssize)
print(rsamples)
#print(videos)

#os.chdir(r'D:\ffmpeg\directorios\experiments')
#videos = glob.glob(r'*.mp4')
#videos.sort(key = len)
#samples = np.genfromtxt(r'D:\ffmpeg\directorios\experiments\scores.csv',usecols=np.arange(0,5))
#vsize = len(videos)
#ssize = len(samples)
#print(vsize)
#print(ssize)
#print(videos)


800
800
[[1.51748]
 [1.67136]
 [1.59087]
 [1.58878]
 [1.50383]
 [1.54585]
 [1.35758]
 [1.60361]
 [1.31151]
 [1.4069 ]
 [1.66856]
 [1.6859 ]
 [1.32858]
 [1.64054]
 [1.42232]
 [1.62876]
 [1.51641]
 [1.42351]
 [1.45175]
 [1.36938]
 [2.15125]
 [2.15857]
 [1.90471]
 [2.04007]
 [2.22824]
 [2.03092]
 [2.00176]
 [2.25229]
 [2.00698]
 [2.07918]
 [2.14629]
 [2.14663]
 [2.07591]
 [2.18394]
 [2.22428]
 [2.28667]
 [2.17472]
 [1.95652]
 [2.25826]
 [1.97041]
 [2.90657]
 [2.70397]
 [2.93171]
 [2.80331]
 [2.70647]
 [2.73717]
 [2.82115]
 [2.98965]
 [2.76903]
 [2.91362]
 [2.75472]
 [2.9659 ]
 [2.99379]
 [2.83849]
 [2.89333]
 [2.94793]
 [2.77293]
 [2.71668]
 [2.80708]
 [2.78176]
 [3.57564]
 [3.52404]
 [3.70366]
 [3.72994]
 [3.57115]
 [3.53699]
 [3.69086]
 [3.59226]
 [3.76949]
 [3.67431]
 [3.76813]
 [3.79795]
 [3.61788]
 [3.736  ]
 [3.63094]
 [3.6269 ]
 [3.71897]
 [3.69784]
 [3.66047]
 [3.77766]
 [4.69689]
 [4.66991]
 [4.65662]
 [4.80827]
 [4.79466]
 [4.53633]
 [4.52977]
 [4.83717]
 [4.68836]
 [4.62156]
 [

In [3]:
def scaleDownVideos(videos):
    for video in videos:
        folder = video.split()[0]
        #print(folder)
        path = 'D:/ffmpeg/directorios/experiments/scaled/'+folder
        #print(path)
        os.system('ffmpeg -i '+video+' -qp 1 -vf scale=320:240 -strict -2 '+path+'')

def extractImages(videos):
    os.chdir(r'D:\ffmpeg\directorios\experiments\scaled')
    videos = glob.glob(r'*.mp4')
    videos.sort(key = len)
    for video in videos:
        folder = video.split()[0]
        #print(folder)
        path = 'D:/ffmpeg/directorios/experiments/images/'+folder
        print(path)
        os.system('ffmpeg -i '+video+' -vf fps=10 '+path+'_%d.png')

In [17]:

#scaleDownVideos(videos)
#extractImages(videos)


D:/ffmpeg/directorios/experiments/images/1.mp4
D:/ffmpeg/directorios/experiments/images/2.mp4
D:/ffmpeg/directorios/experiments/images/3.mp4
D:/ffmpeg/directorios/experiments/images/4.mp4
D:/ffmpeg/directorios/experiments/images/5.mp4
D:/ffmpeg/directorios/experiments/images/6.mp4
D:/ffmpeg/directorios/experiments/images/7.mp4
D:/ffmpeg/directorios/experiments/images/8.mp4
D:/ffmpeg/directorios/experiments/images/9.mp4
D:/ffmpeg/directorios/experiments/images/10.mp4
D:/ffmpeg/directorios/experiments/images/11.mp4
D:/ffmpeg/directorios/experiments/images/12.mp4
D:/ffmpeg/directorios/experiments/images/13.mp4
D:/ffmpeg/directorios/experiments/images/14.mp4
D:/ffmpeg/directorios/experiments/images/15.mp4
D:/ffmpeg/directorios/experiments/images/16.mp4
D:/ffmpeg/directorios/experiments/images/17.mp4
D:/ffmpeg/directorios/experiments/images/18.mp4
D:/ffmpeg/directorios/experiments/images/19.mp4
D:/ffmpeg/directorios/experiments/images/20.mp4
D:/ffmpeg/directorios/experiments/images/21.mp4
D

D:/ffmpeg/directorios/experiments/images/171.mp4
D:/ffmpeg/directorios/experiments/images/172.mp4
D:/ffmpeg/directorios/experiments/images/173.mp4
D:/ffmpeg/directorios/experiments/images/174.mp4
D:/ffmpeg/directorios/experiments/images/175.mp4
D:/ffmpeg/directorios/experiments/images/176.mp4
D:/ffmpeg/directorios/experiments/images/177.mp4
D:/ffmpeg/directorios/experiments/images/178.mp4
D:/ffmpeg/directorios/experiments/images/179.mp4
D:/ffmpeg/directorios/experiments/images/180.mp4
D:/ffmpeg/directorios/experiments/images/181.mp4
D:/ffmpeg/directorios/experiments/images/182.mp4
D:/ffmpeg/directorios/experiments/images/183.mp4
D:/ffmpeg/directorios/experiments/images/184.mp4
D:/ffmpeg/directorios/experiments/images/185.mp4
D:/ffmpeg/directorios/experiments/images/186.mp4
D:/ffmpeg/directorios/experiments/images/187.mp4
D:/ffmpeg/directorios/experiments/images/188.mp4
D:/ffmpeg/directorios/experiments/images/189.mp4
D:/ffmpeg/directorios/experiments/images/190.mp4
D:/ffmpeg/directorio

D:/ffmpeg/directorios/experiments/images/339.mp4
D:/ffmpeg/directorios/experiments/images/340.mp4
D:/ffmpeg/directorios/experiments/images/341.mp4
D:/ffmpeg/directorios/experiments/images/342.mp4
D:/ffmpeg/directorios/experiments/images/343.mp4
D:/ffmpeg/directorios/experiments/images/344.mp4
D:/ffmpeg/directorios/experiments/images/345.mp4
D:/ffmpeg/directorios/experiments/images/346.mp4
D:/ffmpeg/directorios/experiments/images/347.mp4
D:/ffmpeg/directorios/experiments/images/348.mp4
D:/ffmpeg/directorios/experiments/images/349.mp4
D:/ffmpeg/directorios/experiments/images/350.mp4
D:/ffmpeg/directorios/experiments/images/351.mp4
D:/ffmpeg/directorios/experiments/images/352.mp4
D:/ffmpeg/directorios/experiments/images/353.mp4
D:/ffmpeg/directorios/experiments/images/354.mp4
D:/ffmpeg/directorios/experiments/images/355.mp4
D:/ffmpeg/directorios/experiments/images/356.mp4
D:/ffmpeg/directorios/experiments/images/357.mp4
D:/ffmpeg/directorios/experiments/images/358.mp4
D:/ffmpeg/directorio

D:/ffmpeg/directorios/experiments/images/507.mp4
D:/ffmpeg/directorios/experiments/images/508.mp4
D:/ffmpeg/directorios/experiments/images/509.mp4
D:/ffmpeg/directorios/experiments/images/510.mp4
D:/ffmpeg/directorios/experiments/images/511.mp4
D:/ffmpeg/directorios/experiments/images/512.mp4
D:/ffmpeg/directorios/experiments/images/513.mp4
D:/ffmpeg/directorios/experiments/images/514.mp4
D:/ffmpeg/directorios/experiments/images/515.mp4
D:/ffmpeg/directorios/experiments/images/516.mp4
D:/ffmpeg/directorios/experiments/images/517.mp4
D:/ffmpeg/directorios/experiments/images/518.mp4
D:/ffmpeg/directorios/experiments/images/519.mp4
D:/ffmpeg/directorios/experiments/images/520.mp4
D:/ffmpeg/directorios/experiments/images/521.mp4
D:/ffmpeg/directorios/experiments/images/522.mp4
D:/ffmpeg/directorios/experiments/images/523.mp4
D:/ffmpeg/directorios/experiments/images/524.mp4
D:/ffmpeg/directorios/experiments/images/525.mp4
D:/ffmpeg/directorios/experiments/images/526.mp4
D:/ffmpeg/directorio

D:/ffmpeg/directorios/experiments/images/675.mp4
D:/ffmpeg/directorios/experiments/images/676.mp4
D:/ffmpeg/directorios/experiments/images/677.mp4
D:/ffmpeg/directorios/experiments/images/678.mp4
D:/ffmpeg/directorios/experiments/images/679.mp4
D:/ffmpeg/directorios/experiments/images/680.mp4
D:/ffmpeg/directorios/experiments/images/681.mp4
D:/ffmpeg/directorios/experiments/images/682.mp4
D:/ffmpeg/directorios/experiments/images/683.mp4
D:/ffmpeg/directorios/experiments/images/684.mp4
D:/ffmpeg/directorios/experiments/images/685.mp4
D:/ffmpeg/directorios/experiments/images/686.mp4
D:/ffmpeg/directorios/experiments/images/687.mp4
D:/ffmpeg/directorios/experiments/images/688.mp4
D:/ffmpeg/directorios/experiments/images/689.mp4
D:/ffmpeg/directorios/experiments/images/690.mp4
D:/ffmpeg/directorios/experiments/images/691.mp4
D:/ffmpeg/directorios/experiments/images/692.mp4
D:/ffmpeg/directorios/experiments/images/693.mp4
D:/ffmpeg/directorios/experiments/images/694.mp4
D:/ffmpeg/directorio

In [4]:
os.chdir(r'D:\ffmpeg\directorios\experiments\scaled')
videos = glob.glob(r'*.mp4')
videos.sort(key = len)
#print(videos)
score = rsamples
#print(score)
nppath = 'D:/ffmpeg/directorios/experiments/npimages/'
def ImgFromNumpy(videos, score):
    npscorearray = np.zeros((vsize,5))
    for video in videos:
        os.chdir(r'D:/ffmpeg/directorios/experiments/images')
        images = glob.glob(r''+video.split()[0]+'_*.png')
        images.sort(key = len)
        frames = []
        i = 0
        for image in images:
            i+=1
            image = cv2.imread(image)
            image = np.array(image)
            frames.append(image)
        frames = np.array(frames)
        #np.save(nppath+video.split()[0][:-4]+'.npy', frames)
        mi = int(video.split()[0][:-4])
        m = int(np.round(score[mi-1]-1))
        #print(m)
        npscorearray[mi-1][m]= 1
        #print(npscorearray)
        np.save(nppath+video.split()[0][:-4]+'_score.npy', npscorearray[mi-1])     
     
ImgFromNumpy(videos, score)


In [9]:
for video in videos:
    a = np.load(nppath+video.split()[0][:-4]+'_score.npy')
    c = np.load(nppath+video.split()[0][:-4]+'.npy')
    b = len(a)
    print(b)
    print(a)
    print(c.shape)
    print(a.shape)

5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 

5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 1. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 1. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 1. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 1. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 1. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 1. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 

5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 

5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 1. 0. 0. 0.]
(50, 240, 320, 3)
(5,)
5
[1. 0. 0. 0. 0.]
(50, 240, 320, 

5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 1. 0.]
(50, 240, 320, 3)
(5,)
5
[0. 0. 0. 0. 1.]
(50, 240, 320, 3)
(5,)
